Organizer/Controllers/BrokerController.cs
using Organizer.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace Organizer.Controllers
{
    public class BrokerController : Controller
    {
        private OrganizerDbContext db = new OrganizerDbContext();
        // GET: Broker
        public ActionResult ListBrokers()
        {
            List<Broker> brokers = db.Brokers.ToList();
            return View(brokers);
        }
        // GET: Broker
        public ActionResult AddBroker()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddBroker([Bind(Include = "Firstname, Lastname, Mail, PhoneNumber")] Broker broker)
        {
            if (ModelState.IsValid)
            {
                db.Brokers.Add(broker);
                db.SaveChanges();
                return RedirectToAction("ListBrokers");
            }
            return View();
        }
        public ActionResult ProfilBroker(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Broker broker = db.Brokers.Find(id);
            if (broker == null)
            {
                return HttpNotFound();
            }
            return View(broker);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditBroker([Bind(Include = "BrokerID, Firstname, Lastname, Mail, PhoneNumber")] Broker broker)
        {
            if (ModelState.IsValid)
            {
                db.Entry(broker).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("ListBrokers");
            }
            return View("ProfilBroker");
        }
        public ActionResult DeleteBroker(int? id)
        {
            if(id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Broker broker = db.Brokers.Find(id);
            if (broker == null)
            {
                return HttpNotFound();
            }        
            return View(broker);
        }
        public ActionResult Delete(int? id)
        {
            if(id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Broker broker = db.Brokers.Find(id);
            if (broker == null)
            {
                return HttpNotFound();
            }
            db.Entry(broker).State = EntityState.Deleted;
            db.Brokers.Remove(broker);
            db.SaveChanges();
            return RedirectToAction("ListBrokers");
        }       
    }
}

Organizer/Controllers/CustomerController.cs
using Organizer.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace Organizer.Controllers
{
    public class CustomerController : Controller
    {
        private OrganizerDbContext db = new OrganizerDbContext();
        // GET: Customer
        public ActionResult ListCustomers(string search)
        {
            var customerQ = from c in db.Customers select c;
            if(string.IsNullOrEmpty(search))
            {
                customerQ = customerQ.Where(c => c.Firstname.Contains(search) || c.Lastname.Contains(search));
            }
            List<Customer> customers = customerQ.ToList();
            return View(customers);
        }
        // GET: Customer
        public ActionResult AddCustomer()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddCustomer([Bind(Include = "Firstname, Lastname, Mail, PhoneNumber, Budget")] Customer customer)
        {
            if (ModelState.IsValid)
            {
                db.Customers.Add(customer);
                db.SaveChanges();
                return RedirectToAction("ListCustomers");
            }
            return View();
        }
        public ActionResult ProfilCustomer(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Customer customer = db.Customers.Find(id);
            if (customer == null)
            {
                return HttpNotFound();
            }
            return View(customer);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditCustomer([Bind(Include = "CustomerID, Firstname, Lastname, Mail, PhoneNumber, Budget")] Customer customer)
        {
            if (ModelState.IsValid)
            {
                db.Entry(customer).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("ListCustomers");
            }
            return View("ProfilCustomer");
        }
        public ActionResult DeleteCustomer(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Customer customer = db.Customers.Find(id);
            if (customer == null)
            {
                return HttpNotFound();
            }
            return View(customer);
        }
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Customer customer = db.Customers.Find(id);
            if (customer == null)
            {
                return HttpNotFound();
            }
            db.Entry(customer).State = EntityState.Deleted;
            db.Customers.Remove(customer);
            db.SaveChanges();
            return RedirectToAction("ListCustomers");
        }
    }
}

Organizer/Views/Shared/_Layout.cshtml
@{
    Layout = null;
    //dans la rêquete en cours , on regarde l'url et on prend le chemin local, ce qui renvoie le serveur/controlleur
    var url = HttpContext.Current.Request.Url.LocalPath;
    //Last transforme une chaine de caractères se qui se coupe au niveau des '/' et dont les parties se mettent dans les colonnes d'un tableau
    var page = url.Split('/').Last();
}
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="@Url.Content("~/Content/bootstrap.min.css")" rel="stylesheet" />
    <link href="~/Content/jquery.datetimepicker.css" rel="stylesheet" />
    <link href="@Url.Content("~/Content/style.css")" rel="stylesheet" />
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <!-- Navbar content -->
        <div class="container">
            <div class="navbar-header">
                <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarToggler" aria-controls="navbarToggler" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                @Html.ActionLink("AGENDA", "Index", "Home", null, new { @class = "navbar-brand" })
            </div>
            <div id="navbarToggler" class="navbar-collapse collapse">
                <ul class="navbar-nav">
                    <li class="nav-item">@Html.ActionLink("Accueil", "Index", "Home", null, new { @class = "nav-link" + (@page.Equals("Index") || String.IsNullOrEmpty(@page) ? " active" : "") })</li>
                    <li class="nav-item">@Html.ActionLink("Ajouter un courtier", "AddBroker", "Broker", null, new { @class = "nav-link" + (@page.Equals("AddBroker") ? " active" : "") })</li>
                    <li class="nav-item">@Html.ActionLink("Liste courtier", "ListBrokers", "Broker", null, new { @class = "nav-link" + (@page.Equals("listBroker") ? " active" : "") })</li>
                    <li class="nav-item">@Html.ActionLink("Ajouter un client", "AddCustomer", "Customer", null, new { @class = "nav-link" + (@page.Equals("AddCustomer") ? " active" : "") })</li>
                    <li class="nav-item">@Html.ActionLink("Liste clients", "ListCustomers", "Customer", null, new { @class = "nav-link" + (@page.Equals("ListCustomer") ? " active" : "") })</li>
                    <li class="nav-item">@Html.ActionLink("Rendez-Vous", "AddAppointment", "Home", null, new { @class = "nav-link" + (@page.Equals("AddAppointment") ? " active" : "") })</li>
                </ul>
            </div>
        </div>
    </nav>
    @RenderBody()
    <script src="~/Scripts/jquery-3.3.1.min.js"></script>
    <script src="~/Scripts/bootstrap.bundle.min.js"></script>
    <script src="~/Scripts/jquery.datetimepicker.js"></script>
    <script src="~/Scripts/picker.js"></script>
</body>
</html>